# my global config
global:
  scrape_interval: 5s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 10s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).
  #
remote_write:
- url: ${PROM_REMOTE}
  basic_auth:
    username: ${PROM_USER}
    password: ${PROM_PASS} 

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  - job_name: "node"
    static_configs:
      - targets: ["hs.tail9b256.ts.net:9100", "xa.tail9b256.ts.net:9100", "xb.tail9b256.ts.net:9100"]
  - job_name: "energy"
    static_configs:
      - targets: ["127.0.0.1:2112"]
  - job_name: "ping"
    static_configs:
      - targets: ["127.0.0.1:9427"]
